server:
  port: 0 # Random Port : 0

spring:
  application:
    name: push-server

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
  jackson:
    deserialization:
      READ_UNKNOWN_ENUM_VALUES_USING_DEFAULT_VALUE: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  r2dbc:
    url: r2dbc:mysql://localhost:3306/r2test?serverTimezone=KST&characterEncoding=UTF-8
    username: root
    password: 1234
    hibernate:
      ddl-auto: create-drop

eureka:
  instance:
    hostname: localhost
    instance-id : ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}

  client:
    registerWithEureka: true #gateway는 eureka에 등록할필요 없다. gateway는
    fetchRegistry: true #gateway는 eureka가 찾을 필요 없다
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/ # 서버가 가진 위치값